apiVersion: v1
kind: Service
metadata:
  name: {{ include "supplier-chart.fullname" . }}
spec:
  selector:
    app: {{ .Values.apps.predictSupplierApp }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}
