-- 
-- Create the table
--    AIML_SUPPLIER_TREND: Holds the trend data which is used for prediction
--
--SET ECHO OFF
--SET TERMOUT OFF
BEGIN
  EXECUTE IMMEDIATE 'drop table AIML_SUPPLIER_TREND';
EXCEPTION WHEN OTHERS THEN
  NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'drop table AIML_SVM_PS_SETTINGS';
EXCEPTION WHEN OTHERS THEN
  NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'drop table AIML_RF_PS_SETTINGS';
EXCEPTION WHEN OTHERS THEN
  NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'drop table AIML_NB_PS_SETTINGS';
EXCEPTION WHEN OTHERS THEN
  NULL;
END;
/

create table AIML_SUPPLIER_TREND  ( ITEM_DESCRIPTION VARCHAR2(3000), CATEGORY VARCHAR2(512), SUPPLIER VARCHAR2(255));
create table AIML_SVM_PS_SETTINGS ( SETTING_NAME VARCHAR2(30),  SETTING_VALUE VARCHAR2(4000));
create table AIML_RF_PS_SETTINGS  ( SETTING_NAME VARCHAR2(30),  SETTING_VALUE VARCHAR2(4000));
create table AIML_NB_PS_SETTINGS  ( SETTING_NAME VARCHAR2(30),  SETTING_VALUE VARCHAR2(4000));

quit;
