apiVersion: v1
kind: Service
metadata:
  name: supplier-prediction-service
spec:
  selector:
    app: supplier-prediction-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-prediction-app
spec:
  selector:
    matchLabels:
      app: supplier-prediction-app
  replicas: 4
  template:
    metadata:
      labels:
        app: supplier-prediction-app
    spec:
      containers:
      - name: supplier-prediction-container
        image: supplier-prediction-image:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
